### ISSUE TITLE
Can DiVenn be used for scRNA-seq seurat object?

### ISSUE THREAD

**Issue by levinhein** [BCH-RC/DiVenn#12]
Hello! I have disease1 and disease2 scRNA-seq data. Are scRNA-seq/seurat objects applicable to DiVenn?

I generated 2 Upregulated-DEG lists for these two diseases. I want to make a DiVenn plot to visualize the unique and common genes. However, I'm kind of confused how to do this. From the sample data in your website, I just saw 2-column example: first column is gene ID (I think) and 2nd column is "1" or "2". 

I wonder how I can use my gene lists or seurat object for DiVenn or how I can re-organize my date so that it can be inputted to DiVenn. Thank you!

**Comment by sunliang3361** [comment]
Hello, thank you for reaching out. DiVenn also works for single cell RNAseq data and you only need to re-format your gene lists. For the two up-regulated-DEG lists, you still need to have the log2(FC) values. If genes with log2(FC)>0, they should be upregulated and you should use "1", otherwise, you use should "2". Unfortunately, we cannot accept seurat objects directly. 

Best,
Liang

**Comment by levinhein** [comment]
Hello, thank you for your reply. I see, so I just have to make a new data frame with 2 columns? First column is the gene symbol and the second column is just a 1 (to indicate that the gene is upregulated) and 2 (if otherwise).

Thank you for confirming and have a great week!

**Comment by sunliang3361** [comment]
correct
