### ISSUE TITLE
lag/crash during creation of network

### ISSUE THREAD

**Issue by noor-albader** [BCH-RC/DiVenn#2]
Hi
I have 4 input lists, ranging from ~500  to ~7000 genes each and the lag time to center/zoom/click to show label does not work. One cluster is not connected to the other 3 and is impossible to scale the image to capture all 4 clusters. Is there any way to bring the non-connected cluster closer?

Also, I work on rice,  there are no pathway or GO or gene detail information that I can find within the network. Am I using the wrong gene ID format for rice? do I have to input KEGG or GO IDs separately?

Any thoughts?

**Comment by sunliang3361** [comment]
Hi, 
Could you send me your data, so I can check for you? Thank you. My email is lsun@noble.org

**Comment by sunliang3361** [comment]
Hi Noor,
Because one sample has no overlapping genes with the other three samples, that’s why this sample is isolated in the graph and far away from the other three samples (see image file 1). 
Right now, DiVenn works for all supported IDs from KEGG IDs, Uniprot IDs and Entrez IDs for pathway analysis, and works for GO analysis for all AgriGO supported IDs. 
Your IDs are only supported for GO terms analysis.  See the attached image file 2.
Please let me know if you have any further questions. Thanks.
